// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'avatar__icon': string;
  'box': string;
  'button__enter': string;
  'error': string;
  'root': string;
  'typography': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
